project:
  name: infratest
  regions:
    - us-east-1

tests:
  vpc:
    template: infrastructure.yml
    stack_name: infratest-vpc
    regions:
      - us-east-1
    parameters:
      VpcCIDR: 10.0.0.0/16

  subnet:
    template: infrastructure.yml
    stack_name: infratest-subnet
    regions:
      - us-east-1
    parameters:
      VpcCIDR: 10.0.0.0/16
      PublicSubnetCIDR: 10.0.1.0/24
      PrivateSubnetCIDR: 10.0.2.0/24

  instance:
    template: infrastructure.yml
    stack_name: infratest-instance
    regions:
      - us-east-1
    parameters:
      VpcCIDR: 10.0.0.0/16
      PublicSubnetCIDR: 10.0.1.0/24
      PrivateSubnetCIDR: 10.0.2.0/24
      KeyName: Cloud-Formation
      AllowedSSHIP: 0.0.0.0/0