project:
  name: infratest
  regions:
    - us-east-1

tests:
  vpc:
    template: infrastructure.yml
    parameters:
      VpcCIDR: "10.0.0.0/16"
      KeyName: "Cloud-Formation"
    regions:
      - us-east-1
    stack_name: "infratest-vpc"

  public_subnet:
    template: infrastructure.yml
    parameters:
      VpcCIDR: "10.0.0.0/16"
      PublicSubnetCIDR: "10.0.1.0/24"
      KeyName: "Cloud-Formation"
    regions:
      - us-east-1
    stack_name: "infratest-public-subnet"

  private_subnet:
    template: infrastructure.yml
    parameters:
      VpcCIDR: "10.0.0.0/16"
      PrivateSubnetCIDR: "10.0.2.0/24"
      KeyName: "Cloud-Formation"
    regions:
      - us-east-1
    stack_name: "infratest-private-subnet"
