version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install cfn-lint
      - pip install taskcat
  build:
    commands:
      - cd LAB01/CloudFormation
      - cfn-lint infrastructure.yml
      - taskcat test run
artifacts:
  files:
    - "**/*"
