version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install cfn-lint
      - pip install taskcat
  build:
    commands:
      - cfn-lint LAB01/CloudFormation/infrastructure.yml
      - cd LAB01/CloudFormation && taskcat test run
artifacts:
  files:
    - "**/*"
